spring.application.name=jobportal
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
#logging.level.root=${ROOT_LOG_LEVEL:WARN}
logging.level.com.eazybytes.jobportal=${LOG_LEVEL:WARN}

#logging.file.name=logs/jobportallogs.log
#logging.pattern.file={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}

# H2 Database configuration
#####################
# Below In-Memory Database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.enabled=true
#spring.sql.init.mode=EMBEDDED
#spring.sql.init.mode=always
#spring.sql.init.mode=NEVER
#spring.sql.init.schema-locations=classpath:sql/jobportal-schema.sql
#spring.sql.init.data-locations=optional:classpath:sql/jobportal-data.sql

# MySQL Database configuration
########################
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:jobportal}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.default_batch_fetch_size=${DEFAULT_BATCH_FETCH_SIZE:50}
spring.jpa.hibernate.ddl-auto=none

# Docker Compose configuration
#########################
spring.docker.compose.file=jobportal-compose.yml
spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.start.command= up
spring.docker.compose.stop.command= stop

#docker run mysql:latest-> used to download the image and create a container
#docker compose up ->used to download the images if not existing and create the containers as per the configuration in the docker-compose file
#docker compose down -> used to stop and remove the containers created by docker compose up command
#docker compose start -> used to start the existing stopped containers created by docker compose up command
#docker compose stop -> used to stop the running containers created by docker compose up command

#Spring Security configuration
########################
#spring.security.user.name= naresh
#spring.security.user.password=naresh123
#spring.security.user.roles= USER, ADMIN